spring.application.name=icsd-prac
server.port=9981

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/free
spring.datasource.username=C##SPRINGWALLET
spring.datasource.password=icsd
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

file.upload-dir = D:/LOCAL_STORAGE
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hardikgautam1606@gmail.com
spring.mail.password=wltiurxsrvrraoug
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.plan.basic.expiry-days=15



spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


spring.jpa.properties.hibernate.generate_statistics=true